apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  strategy:
    type: Recreate # trivially avoids multi-mount error on persistent volumes in exchange for some downtime
  template:
    spec:
      containers:
        - name: pg
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
            - name: POSTGRES_USER
            - name: POSTGRES_PASSWORD
            - # NOTE: using a subfolder is required to avoid permission problems
              name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources: {}
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pvc
