apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress
spec:
  rules:
    - host: lt.eurac.edu
      http:
        paths:
          - path: /oetzit/backend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  name: http
  tls:
    - hosts:
        - lt.eurac.edu
      secretName: lt-prd-tls
