version: '3.7'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: oetzi-backend-dev
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    command: npm run serve
