version: '3.7'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    command: npm run start
