apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - webserver.ingress.yaml
commonLabels:
  eurac.edu/environment: dev
  app.kubernetes.io/part-of: oetzit
  app.kubernetes.io/managed-by: kustomize
patchesStrategicMerge:
  - database.deployment.yaml
  - webserver.deployment.yaml
images:
  - name: oetzit-webserver-image
    # NOTE: use `minikube image load oetzit:latest` to push into container runtime
    newName: oetzit
    newTag: latest
secretGenerator:
  - literals:
      - username=db_user
      - password=db_pass
      - database=db_name
      - url=postgres://db_user:db_pass@oetzit-database-service/db_name
    name: oetzit-database-credentials
    type: Opaque
