apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  eurac.edu/environment: dev
  app.kubernetes.io/part-of: oetzi
  app.kubernetes.io/managed-by: kustomize
patchesStrategicMerge:
  - database.deployment.yaml
  - webserver.deployment.yaml
images:
  - name: oetzi-webserver-image
    # NOTE: use `minikube image load oetzi:latest` to push into container runtime
    newName: oetzi
    newTag: latest
secretGenerator:
  - literals:
      - username=db_user
      - password=db_pass
      - database=db_name
      - url=postgres://db_user:db_pass@oetzi-database-service/db_name
    name: oetzi-database-credentials
    type: Opaque
patchesJSON6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: oetzi-webserver-ingress
    path: webserver.ingress.patch.yaml
