kind: Kustomization
resources:
  - ../../base
namespace: kommul-dev
commonLabels:
  eurac.edu/environment: dev
  app.kubernetes.io/part-of: oetzi
  app.kubernetes.io/managed-by: kustomize
patchesStrategicMerge:
  - database.deployment.yaml
  - webserver.deployment.yaml
images:
  - name: oetzi-webserver-image
    newName: gitlab.inf.unibz.it:4567/commul/oetzi/backend
    newTag: latest
secretGenerator:
  # TODO: avoid using literals
  - literals:
      - username=db_user
      - password=db_pass
      - database=db_name
      - url=postgres://db_user:db_pass@oetzi-database-service/db_name
    name: oetzi-database-credentials
    type: Opaque
patchesJSON6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: oetzi-webserver-ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1rewrite-target
        value: /$2
      - op: replace
        path: /spec/rules/0/host
        value: kommul-dev.eurac.edu
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /oetzi(/|$)(.*)
