apiVersion: apps/v1
kind: Deployment
metadata:
  name: oetzi-database-deployment
spec:
  template:
    spec:
      containers:
        - name: pg
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: oetzi-database-credentials
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: oetzi-database-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oetzi-database-credentials
                  key: username
