apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - webserver.ingress.yaml
namespace: kommul-dev
commonLabels:
  eurac.edu/environment: stg
  app.kubernetes.io/part-of: oetzit
  app.kubernetes.io/managed-by: kustomize
patchesStrategicMerge:
  - database.deployment.yaml
  - webserver.deployment.yaml
images:
  - name: oetzit-webserver-image
    newName: gitlab.inf.unibz.it:4567/commul/oetzit/backend
    newTag: latest
secretGenerator:
  # TODO: avoid using literals
  - literals:
      - username=db_user
      - password=db_pass
      - database=db_name
      - url=postgres://db_user:db_pass@oetzit-database-service/db_name
    name: oetzit-database-credentials
    type: Opaque
