apiVersion: apps/v1
kind: Deployment
metadata:
  name: oetzit-storage-deployment
spec:
  template:
    spec:
      containers:
        - name: minio
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: oetzit-storage-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oetzit-storage-credentials
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_BROWSER_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: oetzit-storage-credentials
                  key: MINIO_BROWSER_REDIRECT_URL
