apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: pg
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
            - name: POSTGRES_USER
            - name: POSTGRES_PASSWORD
          resources: {}
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pvc
