kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
namePrefix: database-
commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/component: database
  app.kubernetes.io/managed-by: kustomize
