kind: Kustomization
resources:
  - database-deployment.yaml
  - database-pvc.yaml
  - database-service.yaml
  - webserver-deployment.yaml
  - webserver-ingress.yaml
  - webserver-service.yaml
# namespace: kommul-dev
namePrefix: oetzi-
commonLabels:
  app: oetzi
