apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
namePrefix: deployer-
commonLabels:
  app.kubernetes.io/name: deployer
  app.kubernetes.io/component: deployer
