apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
rules:
  - # NOTE: this is the bare minimum for a `kubectl set image` on a deployment
    apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list"]
