apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
subjects:
  - kind: ServiceAccount
    name: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
