apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: oetzi
          image: oetzi-webserver-image
          resources: {}
          ports:
            - name: http
              containerPort: 80
          command: ["npm", "run", "serve"]
          env:
            - name: PORT
              value: "80"
            - name: DATABASE_URL
