apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: oetzit
          image: oetzit-webserver-image
          resources: {}
          ports:
            - name: http
              containerPort: 80
          command: ["npm", "run", "serve"]
          env: &env
            - name: PORT
              value: "80"
            - name: DATABASE_URL
      initContainers:
        - name: oetzit-migrator
          image: oetzit-webserver-image
          resources: {}
          command: ["npm", "exec", "knex", "migrate:latest"]
          env: *env # TODO: use configMap?
