apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: PLACEHOLER
      http:
        paths:
          - path: PLACEHOLDER
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  name: http
