apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base
namespace: stg-oetzit
commonLabels:
  eurac.edu/environment: stg
  app.kubernetes.io/part-of: oetzit
  app.kubernetes.io/managed-by: kustomize
patchesStrategicMerge:
  - database.deployment.yaml
  - webserver.deployment.yaml
  - webserver.ingress.yaml
  - storage.deployment.yaml
  - storage.ingress.yaml
images:
  - name: backend-image
    newName: re.eurac.edu/commul/oetzit/backend
    newTag: development
    # newName: re.eurac.edu/commul/az/helloworld
    # newTag: latest
secretGenerator:
  - envs:
      - database.secret.env
    name: database-secret
    type: Opaque
  - envs:
      - dashboard.secret.env
    name: dashboard-secret
    type: Opaque
  - envs:
      - storage.secret.env
    name: storage-secret
    type: Opaque
