apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  #- ingress.yaml
  - service.yaml
namePrefix: webserver-
commonLabels:
  app.kubernetes.io/name: nodejs
  app.kubernetes.io/component: webserver
