---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

namePrefix: merlin-platform-
# nameSuffix: -v1
commonLabels:
  variant: staging
  org: commul
  app: merlin-webpage
commonAnnotations:
  note: merlin-platform-note
namespace: kommul-dev

images:
  - name: WEBSERVER
    newName: gitlab.inf.unibz.it:4567/commul/merlin-platform/www/master:445bc35dde4520cab61a36c793c7c5a626f43e62

patchesJSON6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/ingress.kubernetes.io~1configuration-snippet
        value: |
          rewrite ^(/merlin)$ $1/ permanent;
      - op: replace
        path: /spec/rules/0/host
        value: kommul-dev.eurac.edu
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /merlin
      - op: replace
        path: /spec/tls/0/secretName
        value: kommul-dev.eurac.edu-merlin-tls
