apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./database
  - ./deployer
  - ./webserver
  - ./storage
  - dockerconfigjson.secret.yaml
commonLabels:
  app.kubernetes.io/part-of: oetzit
  app.kubernetes.io/managed-by: kustomize
